### ISSUE TITLE
copying breaks singleton functionality

### ISSUE THREAD

**Issue by jkornelsen** [grantjenks/python-tribool#1]
According to the documentation, `Instances with the same value are identical (singleton-like).`  However the following occurs:

```
>>> from tribool import Tribool
>>> import copy
>>> a = Tribool(True)
>>> b = copy.copy(a)
>>> a
Tribool(True)
>>> b
Tribool(True)
>>> a is b
False
```

This caused an error in my project when a data structure containing a nested Tribool was deep copied.

I made a fix to this problem in a git repo and added a test.  If you add my account as a github collaborator, then I could push it as a separate branch for you to review.

**Comment by grantjenks** [comment]
Thanks for the bug report. Can you create a pull request? https://help.github.com/articles/using-pull-requests/

**Comment by jkornelsen** [comment]
Done.

**Comment by grantjenks** [comment]
Dup of #2
